# Generated by Django 4.2.7 on 2025-12-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fieldresponse",
            options={
                "verbose_name": "Field Response",
                "verbose_name_plural": "Field Responses",
            },
        ),
        migrations.AlterModelOptions(
            name="form",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="formfield",
            options={
                "ordering": ["order"],
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="formsubmission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
            },
        ),
        migrations.AlterField(
            model_name="fieldresponse",
            name="field",
            field=models.ForeignKey(
                help_text="Field this response is for",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.formfield",
            ),
        ),
        migrations.AlterField(
            model_name="fieldresponse",
            name="submission",
            field=models.ForeignKey(
                help_text="Submission this response belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="api.formsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="fieldresponse",
            name="value",
            field=models.TextField(help_text="The response value"),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when form was created"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this form",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the form"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the form is active and accepting submissions",
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="title",
            field=models.CharField(help_text="Title of the form", max_length=200),
        ),
        migrations.AlterField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when form was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("textarea", "Textarea"),
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                    ("file", "File"),
                ],
                help_text="Type of input field",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="form",
            field=models.ForeignKey(
                help_text="Form this field belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="api.form",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="label",
            field=models.CharField(
                help_text="Label displayed for this field", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="options",
            field=models.JSONField(
                blank=True,
                help_text="Options for select, radio, or checkbox fields",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order of the field"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="placeholder",
            field=models.CharField(
                blank=True, help_text="Placeholder text for the input", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="required",
            field=models.BooleanField(
                default=False, help_text="Whether this field is required"
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="form",
            field=models.ForeignKey(
                help_text="Form this submission belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="api.form",
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the submitter", null=True
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when submission was created"
            ),
        ),
    ]
